# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenericEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.IntegerField(choices=[(0, 'Bicycle'), (1, 'Push Cart'), (2, 'Chest Freezer'), (3, 'Refridgerator')])),
                ('serial_number', models.CharField(max_length=30)),
                ('commission_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'OK'), (1, 'Broken')])),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault', models.CharField(max_length=1024)),
                ('date_sent', models.DateField()),
                ('date_received', models.DateField()),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.GenericEquipment')),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=1, max_digits=2)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.GenericEquipment')),
            ],
        ),
    ]
