# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-28 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0001_initial'),
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('cheque_date', models.DateField()),
                ('cheque_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DayPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('purchase_type', models.IntegerField(choices=[(0, 'CASH'), (1, 'CREDIT')], default=1)),
                ('invoice_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('payment_type', models.IntegerField(choices=[(0, 'CASH'), (1, 'CHEQUE')], default=1)),
                ('amount_paid', models.FloatField()),
                ('cheque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.Cheque')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('master_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.DayPurchase')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Product')),
            ],
        ),
        migrations.AddField(
            model_name='daypurchase',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.ProductPayment'),
        ),
        migrations.AddField(
            model_name='daypurchase',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Shop'),
        ),
    ]
