# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daypurchase',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='daypurchase',
            name='purchase_type',
            field=models.IntegerField(choices=[(0, 'Credit Purchase'), (1, 'Cash Purchase')], default=1),
        ),
        migrations.AlterField(
            model_name='productpayment',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'Cheque Payment'), (1, 'Cash Payment')], default=1),
        ),
    ]
