# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 00:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_auto_20170316_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daypurchase',
            options={'ordering': ['-date']},
        ),
    ]
