# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_auto_20170324_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='daypurchase',
            name='total',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
