# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_auto_20170403_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daypurchase',
            old_name='p_month',
            new_name='month',
        ),
    ]
