# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-05 11:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20170401_1610'),
        ('utils', '0003_auto_20170316_0450'),
        ('purchases', '0007_auto_20170403_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('month', models.IntegerField()),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductDamage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('master_damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.DamageCount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Product')),
            ],
        ),
    ]
