# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('hometown', models.CharField(max_length=100)),
                ('guarantor', models.CharField(max_length=100)),
                ('relation', models.CharField(max_length=100)),
                ('guarantor_phone', models.CharField(max_length=50)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Shop')),
            ],
        ),
    ]
