# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 00:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='shop',
        ),
        migrations.AddField(
            model_name='vendor',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
    ]
