# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20170324_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='profile',
            field=models.ImageField(blank=True, default='static/profiles/default.png', upload_to='static/profiles/'),
        ),
    ]
