# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0005_vendor_guarantor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
