# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-30 21:19
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_vendor_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='profile',
            field=sorl.thumbnail.fields.ImageField(blank=True, default='static/profiles/default.png', upload_to='static/profiles/'),
        ),
    ]
