# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-10 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20170401_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='agent',
        ),
        migrations.AddField(
            model_name='vendor',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agent.Shop'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='profile',
            field=models.ImageField(blank=True, default='profiles/default.png', upload_to='profiles/'),
        ),
    ]
