# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-11 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_auto_20190210_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='agent.Shop'),
        ),
    ]
