# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-01 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utils', '0003_auto_20170316_0450'),
        ('agent', '0008_auto_20170401_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.IntegerField()),
                ('returns', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VendorBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('closed', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('amount_paid', models.NullBooleanField()),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Vendor')),
            ],
        ),
        migrations.AddField(
            model_name='productbooking',
            name='master_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.VendorBooking'),
        ),
        migrations.AddField(
            model_name='productbooking',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils.Product'),
        ),
    ]
