# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbooking',
            name='total',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='vendorbooking',
            name='amount_paid',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
