# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 00:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbooking',
            name='master_booking',
        ),
        migrations.RemoveField(
            model_name='productbooking',
            name='product',
        ),
        migrations.RemoveField(
            model_name='vendorbooking',
            name='vendor',
        ),
        migrations.DeleteModel(
            name='ProductBooking',
        ),
        migrations.DeleteModel(
            name='VendorBooking',
        ),
    ]
