# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbooking',
            old_name='m_amount_paid',
            new_name='amount_paid',
        ),
    ]
