# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 23:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20170425_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorbooking',
            old_name='amount_paid',
            new_name='m_amount_paid',
        ),
    ]
